micronaut:
  server:
    cors:
      enabled: true
      configurations:
        web:
          allowedOrigins:
            - http://localhost:4200
          exposedHeaders:
            - HttpHeaders.ACCESS_CONTROL_ALLOW_ORIGIN