micronaut:
  application:
    name: server
server:
  cors:
    enabled: true
configurations:
  web:
    allowedOrigins:
      - http://localhost:4200
allowedMethods:
  - POST
  - GET
exposedHeaders:
  - Content-Type
  - Authorization
  - Cache-Control
  - Cache-Control
  - Content-Language
  - Content-Type
  - Expires
  - Last-Modified
  - Pragma